name: Deploy API Queries to Cloud Run

on:
  push:
    branches:
      - main  # o la rama que uses para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'  # Debes crear este secret en GitHub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t prueba_cloudrun:1.0.0 . --load

      - name: Tag Docker image
        run: |
          docker tag prueba_cloudrun:1.0.0 us-central1-docker.pkg.dev/dm-data-aiml/test-images-repo/prueba_cloudrun:1.0.0

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/dm-data-aiml/test-images-repo/prueba_cloudrun:1.0.0

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy prueba-cloudrun \
            --image=us-central1-docker.pkg.dev/dm-data-aiml/test-images-repo/prueba_cloudrun:1.0.0 \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --project=dm-data-aiml \
            --service-account=dm-data-aiml@dm-data-aiml.iam.gserviceaccount.com